Repository DO-NOTTO-DO/NotToDo-server, pull requests merged in 2023-01, with the labels that each got.

#14 feat: #12 add fcm_token table
  prisma/schema.prisma
Labels: feat

#22 Feat/#15 일일 낫투두 조회 API 구현
  package.json
  prisma/schema.prisma
  src/DTO/actionDTO.ts
  src/DTO/missionDTO.ts
  src/constants/responseMessage.ts
  src/controllers/index.ts
  src/controllers/missionController.ts
  src/modules/dateValidator.ts
  src/router/index.ts
  src/router/missionRouter.ts
  src/service/index.ts
  src/service/missionService.ts
Labels: API

#27 Feat/#23 주간 낫투두 개수 조회
  src/constants/responseMessage.ts
  src/controllers/missionController.ts
  src/modules/dateValidator.ts
  src/router/missionRouter.ts
  src/service/missionService.ts
Labels: API

#30 Feat/#29 낫투두 상태 변경 API
  src/constants/responseMessage.ts
  src/controllers/missionController.ts
  src/modules/dateValidator.ts
  src/modules/missionValidator.ts
  src/router/missionRouter.ts
  src/service/missionService.ts
Labels: API

#34 Feat/#33 푸시 알림 구현
  .gitignore
  package.json
  src/config/index.ts
  src/index.ts
  src/loaders/mongoDB.ts
  src/service/pushAlarmService.ts
Labels: feat

#42 feat: GET /mission/recent 낫투두 최근 기록 조회
  src/constants/responseMessage.ts
  src/controllers/missionController.ts
  src/router/missionRouter.ts
  src/service/missionService.ts
Labels: pull request

#38 feat: #37 filter to exclude NOTYET
  src/service/missionService.ts
Labels: fix

#45 feat: POST /:missionId 다른날짜에 낫투두 추가
  src/constants/responseMessage.ts
  src/controllers/missionController.ts
  src/modules/dateValidator.ts
  src/router/missionRouter.ts
  src/service/missionService.ts
Labels: pull request

#46 Feat/#44 배너 조회 API 제작
  package.json
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controllers/bannerController.ts
  src/controllers/index.ts
  src/modules/koreanTimeConverter.ts
  src/modules/shuffleBanner.ts
  src/router/bannerRouter.ts
  src/router/index.ts
  src/service/bannerService.ts
Labels: API

#49 feat: #28 POST /mission 낫투두 추가
  prisma/schema.prisma
  src/DTO/missionDTO.ts
  src/constants/responseMessage.ts
  src/controllers/missionController.ts
  src/middlewares/validator.ts
  src/router/missionRouter.ts
  src/service/missionService.ts
Labels: pull request

#52 fix: #51 날짜 이슈 해결
  src/controllers/missionController.ts
  src/service/missionService.ts
Labels: pull request

#50 Feat/#40 박정훈 테스트 코드
  package.json
  prisma/schema.prisma
  src/test/banner.spec.ts
  src/test/mission.spec.ts
Labels: test

#56 feat: #55 낫투두 추가, 낫투두 다른날짜에 추가, 상황조회, 최근기록 조회
  src/test/mission.spec.ts
  src/test/situation.spec.ts
Labels: test
